### ISSUE TITLE
preview the content under point

### ISSUE THREAD

**Issue by randomwangran** [nobiot/org-marginalia#1]
Thanks for grouping this package. I find the ability to connect
Org-mode notes is extremely useful. The format saving the
annotations in Org-mode format is also intuitive for me, so it
can be easily incorporated into Org-roam.

After a very short interaction with the code, I found something
that might be useful. I jot down them in the issue tracker
but do not feel any pressure on it. I am also trying to implement
these features as well.

I find that we need to use `om/open` to open the notes.

I believe when the marker is visiting a marked object, it can
prompt up the content of the associated annotation.

I will try to play with it using `posframe`.

**Comment by randomwangran** [comment]
By the way, which platform do you prefer? Org-roam discourse or GH issue tracker?

**Comment by nobiot** [comment]
I guess for this topic, we can share our conversations with OR community - this is about note taking and a tool that can be used as an extension to OR.

**Comment by nobiot** [comment]
and thanks for the comment. 

I see that many people find a pop-up for editing margin notes useful. As tor this package, I would like to avoid dependency on another package. I am hoping that you can "hook up" a post frame or anything without changing the source. Let me know if there is something I can change to make it easy/possible.

**Comment by randomwangran** [comment]
Okay, I will put the discussion on OR. 

If any technical issues, I will send them here when I am hooking up a posframe.
