### ISSUE TITLE
Default keybindings

### ISSUE THREAD

**Issue by karthink** [nobiot/org-marginalia#3]
This is a suggestion about the default keybindings ("C-c n" map). The Emacs [key binding guidelines](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html) say:

> Don’t define C-c letter as a key in Lisp programs. Sequences consisting of C-c and a letter (either upper or lower case) are reserved for users; they are the only sequences reserved for users, so do not block them.
> Changing all the Emacs major modes to respect this convention was a lot of work; abandoning this convention would make that work go to waste, and inconvenience users. Please comply with it.

I believe `org-roam` suggests `C-c n` bindings but doesn't bake them into `org-roam.el`. 

Can this be changed to something else?

**Comment by nobiot** [comment]
Thanks. Sure, happy to. Any suggestions?
I can also remove all the default keybindings to make them completely left for anyone who uses it. Perhaps that’s the easiest.

**Comment by karthink** [comment]
I think what `org-roam` does is pretty good. The keymap is empty in `org-roam.el` but the use-package declaration in the README binds various commands to the `C-c n` keymap.

**Comment by nobiot** [comment]
Thank you for the suggestion. Let me see what I can do. I'll come back after a little belated X'mas break :) Have a great weekend!

**Comment by nobiot** [comment]
@karthink a Happy New Year to you. Took your advice. Removed default keybidings; added examples in [README](https://github.com/nobiot/org-marginalia#keybindings-examples).
