### ISSUE TITLE
turning off the mode should turn off the overlays

### ISSUE THREAD

**Issue by holtzermann17** [nobiot/org-marginalia#5]
![Screenshot from 2020-12-27 02-13-13](https://user-images.githubusercontent.com/179958/103162486-1e864480-47e9-11eb-974a-fa6128037cae.png)

Screenshot: I just disabled the mode but the overlays remain

**Comment by shombando** [comment]
@holtzermann17 looks like this is a recognized limitation by the author:

> Turning off minor mode does not turn off the highlights

> This should not do any harm, but if you are distracted, kill the buffer (not revert) and visit it again. Toggling show/hide of highlights is something I would like to add later.

Would be interesting to prompt the user to reload buffer (at least current buffer) assuming buffer is unmodified when turning off the minor mode.

**Comment by nobiot** [comment]
v0.0.6 does this. 
README:
> Now turning off minor mode will turn off the highlights
>     It is still recommended to use org-marginalia-toggle to temporarily hide/show highlights. This is because turning off org-marginalia-mode will stop tracking of the locations of highlights in the current buffer. **Any** (however minor) change will likely result in mismatching the locations of saved highlights and the current buffer’s text content.
